name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker run -v $(pwd):/root/enjoy --cap-add=SYS_ADMIN davidva/unibuild-34 /bin/sh -c "rm -f urpms && wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/urpms && chmod a+x urpms && /urpms -g UnitedRPMs/xorg-x11-utils -s xorg-x11-utils.spec -r true -d 'dist .fc34' -u true"
